name: Update Recent Tracks

on:
  schedule:
    - cron: "0 * * * *"  # 毎時実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch recent tracks from Last.fm
        run: |
          mkdir -p dist
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="140"><rect width="100%" height="100%" fill="black"/><g fill="lime" font-family="monospace" font-size="14">' > dist/recent.svg
          curl -s "http://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=YOUR_USERNAME&api_key=${{ secrets.LASTFM_API_KEY }}&format=json&limit=5" \
          | jq -r '.recenttracks.track[] | "\(.artist[\"#text\"]) - \(.name)"' \
          | awk '{print "<text x=\"10\" y=" 20+20*NR ">" $0 "</text>"}' >> dist/recent.svg
          echo '</g></svg>' >> dist/recent.svg

      - name: Deploy SVG to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
    
      - name: Debug Last.fm response
        run: |
          curl -s "http://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=YOUR_USERNAME&api_key=${{ secrets.LASTFM_API_KEY }}&format=json&limit=2" | jq .
